/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeRouteImport } from './routes/time'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as StopwatchRouteImport } from './routes/stopwatch'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PomodoroRouteImport } from './routes/pomodoro'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as LearnProgressRouteImport } from './routes/learn.progress'
import { Route as LearnProblemsRouteImport } from './routes/learn.problems'
import { Route as LearnInsightsRouteImport } from './routes/learn.insights'
import { Route as LearnConceptsRouteImport } from './routes/learn.concepts'
import { Route as FinanceTransactionsRouteImport } from './routes/finance.transactions'
import { Route as FinanceSavingsRouteImport } from './routes/finance.savings'
import { Route as FinanceCategoriesRouteImport } from './routes/finance.categories'
import { Route as FinanceBudgetsRouteImport } from './routes/finance.budgets'
import { Route as FinanceAnalyticsRouteImport } from './routes/finance.analytics'
import { Route as FinanceAccountsRouteImport } from './routes/finance.accounts'

const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const StopwatchRoute = StopwatchRouteImport.update({
  id: '/stopwatch',
  path: '/stopwatch',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PomodoroRoute = PomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const LearnProgressRoute = LearnProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => LearnRoute,
} as any)
const LearnProblemsRoute = LearnProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => LearnRoute,
} as any)
const LearnInsightsRoute = LearnInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LearnRoute,
} as any)
const LearnConceptsRoute = LearnConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => LearnRoute,
} as any)
const FinanceTransactionsRoute = FinanceTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceSavingsRoute = FinanceSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceCategoriesRoute = FinanceCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceBudgetsRoute = FinanceBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAnalyticsRoute = FinanceAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAccountsRoute = FinanceAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => FinanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRouteWithChildren
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRouteWithChildren
  '/notes': typeof NotesRoute
  '/pomodoro': typeof PomodoroRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/stopwatch': typeof StopwatchRoute
  '/tags': typeof TagsRoute
  '/tasks': typeof TasksRoute
  '/time': typeof TimeRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/analytics': typeof FinanceAnalyticsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/savings': typeof FinanceSavingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/learn/concepts': typeof LearnConceptsRoute
  '/learn/insights': typeof LearnInsightsRoute
  '/learn/problems': typeof LearnProblemsRoute
  '/learn/progress': typeof LearnProgressRoute
  '/finance/': typeof FinanceIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/journal': typeof JournalRoute
  '/notes': typeof NotesRoute
  '/pomodoro': typeof PomodoroRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/stopwatch': typeof StopwatchRoute
  '/tags': typeof TagsRoute
  '/tasks': typeof TasksRoute
  '/time': typeof TimeRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/analytics': typeof FinanceAnalyticsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/savings': typeof FinanceSavingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/learn/concepts': typeof LearnConceptsRoute
  '/learn/insights': typeof LearnInsightsRoute
  '/learn/problems': typeof LearnProblemsRoute
  '/learn/progress': typeof LearnProgressRoute
  '/finance': typeof FinanceIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRouteWithChildren
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRouteWithChildren
  '/notes': typeof NotesRoute
  '/pomodoro': typeof PomodoroRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/stopwatch': typeof StopwatchRoute
  '/tags': typeof TagsRoute
  '/tasks': typeof TasksRoute
  '/time': typeof TimeRoute
  '/finance/accounts': typeof FinanceAccountsRoute
  '/finance/analytics': typeof FinanceAnalyticsRoute
  '/finance/budgets': typeof FinanceBudgetsRoute
  '/finance/categories': typeof FinanceCategoriesRoute
  '/finance/savings': typeof FinanceSavingsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/learn/concepts': typeof LearnConceptsRoute
  '/learn/insights': typeof LearnInsightsRoute
  '/learn/problems': typeof LearnProblemsRoute
  '/learn/progress': typeof LearnProgressRoute
  '/finance/': typeof FinanceIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/finance'
    | '/focus'
    | '/goals'
    | '/journal'
    | '/learn'
    | '/notes'
    | '/pomodoro'
    | '/projects'
    | '/settings'
    | '/stopwatch'
    | '/tags'
    | '/tasks'
    | '/time'
    | '/finance/accounts'
    | '/finance/analytics'
    | '/finance/budgets'
    | '/finance/categories'
    | '/finance/savings'
    | '/finance/transactions'
    | '/learn/concepts'
    | '/learn/insights'
    | '/learn/problems'
    | '/learn/progress'
    | '/finance/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/focus'
    | '/goals'
    | '/journal'
    | '/notes'
    | '/pomodoro'
    | '/projects'
    | '/settings'
    | '/stopwatch'
    | '/tags'
    | '/tasks'
    | '/time'
    | '/finance/accounts'
    | '/finance/analytics'
    | '/finance/budgets'
    | '/finance/categories'
    | '/finance/savings'
    | '/finance/transactions'
    | '/learn/concepts'
    | '/learn/insights'
    | '/learn/problems'
    | '/learn/progress'
    | '/finance'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/finance'
    | '/focus'
    | '/goals'
    | '/journal'
    | '/learn'
    | '/notes'
    | '/pomodoro'
    | '/projects'
    | '/settings'
    | '/stopwatch'
    | '/tags'
    | '/tasks'
    | '/time'
    | '/finance/accounts'
    | '/finance/analytics'
    | '/finance/budgets'
    | '/finance/categories'
    | '/finance/savings'
    | '/finance/transactions'
    | '/learn/concepts'
    | '/learn/insights'
    | '/learn/problems'
    | '/learn/progress'
    | '/finance/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  FocusRoute: typeof FocusRoute
  GoalsRoute: typeof GoalsRoute
  JournalRoute: typeof JournalRoute
  LearnRoute: typeof LearnRouteWithChildren
  NotesRoute: typeof NotesRoute
  PomodoroRoute: typeof PomodoroRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  StopwatchRoute: typeof StopwatchRoute
  TagsRoute: typeof TagsRoute
  TasksRoute: typeof TasksRoute
  TimeRoute: typeof TimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stopwatch': {
      id: '/stopwatch'
      path: '/stopwatch'
      fullPath: '/stopwatch'
      preLoaderRoute: typeof StopwatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomodoro': {
      id: '/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof PomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/learn/progress': {
      id: '/learn/progress'
      path: '/progress'
      fullPath: '/learn/progress'
      preLoaderRoute: typeof LearnProgressRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/problems': {
      id: '/learn/problems'
      path: '/problems'
      fullPath: '/learn/problems'
      preLoaderRoute: typeof LearnProblemsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/insights': {
      id: '/learn/insights'
      path: '/insights'
      fullPath: '/learn/insights'
      preLoaderRoute: typeof LearnInsightsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/concepts': {
      id: '/learn/concepts'
      path: '/concepts'
      fullPath: '/learn/concepts'
      preLoaderRoute: typeof LearnConceptsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/finance/transactions': {
      id: '/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof FinanceTransactionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/savings': {
      id: '/finance/savings'
      path: '/savings'
      fullPath: '/finance/savings'
      preLoaderRoute: typeof FinanceSavingsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/categories': {
      id: '/finance/categories'
      path: '/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof FinanceCategoriesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/budgets': {
      id: '/finance/budgets'
      path: '/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof FinanceBudgetsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/analytics': {
      id: '/finance/analytics'
      path: '/analytics'
      fullPath: '/finance/analytics'
      preLoaderRoute: typeof FinanceAnalyticsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/accounts': {
      id: '/finance/accounts'
      path: '/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof FinanceAccountsRouteImport
      parentRoute: typeof FinanceRoute
    }
  }
}

interface FinanceRouteChildren {
  FinanceAccountsRoute: typeof FinanceAccountsRoute
  FinanceAnalyticsRoute: typeof FinanceAnalyticsRoute
  FinanceBudgetsRoute: typeof FinanceBudgetsRoute
  FinanceCategoriesRoute: typeof FinanceCategoriesRoute
  FinanceSavingsRoute: typeof FinanceSavingsRoute
  FinanceTransactionsRoute: typeof FinanceTransactionsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAccountsRoute: FinanceAccountsRoute,
  FinanceAnalyticsRoute: FinanceAnalyticsRoute,
  FinanceBudgetsRoute: FinanceBudgetsRoute,
  FinanceCategoriesRoute: FinanceCategoriesRoute,
  FinanceSavingsRoute: FinanceSavingsRoute,
  FinanceTransactionsRoute: FinanceTransactionsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface LearnRouteChildren {
  LearnConceptsRoute: typeof LearnConceptsRoute
  LearnInsightsRoute: typeof LearnInsightsRoute
  LearnProblemsRoute: typeof LearnProblemsRoute
  LearnProgressRoute: typeof LearnProgressRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnConceptsRoute: LearnConceptsRoute,
  LearnInsightsRoute: LearnInsightsRoute,
  LearnProblemsRoute: LearnProblemsRoute,
  LearnProgressRoute: LearnProgressRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  FinanceRoute: FinanceRouteWithChildren,
  FocusRoute: FocusRoute,
  GoalsRoute: GoalsRoute,
  JournalRoute: JournalRoute,
  LearnRoute: LearnRouteWithChildren,
  NotesRoute: NotesRoute,
  PomodoroRoute: PomodoroRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  StopwatchRoute: StopwatchRoute,
  TagsRoute: TagsRoute,
  TasksRoute: TasksRoute,
  TimeRoute: TimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
